### ISSUE TITLE
Sample example?

### ISSUE THREAD

**Issue by alonsopg** [moddabiri/minibatch#1]
This looks very useful, could you provide a sample example of usage with scikit-learn's `fit()` function?.

**Comment by moddabiri** [comment]
Hi, I added some very basic samples to the project, hope that helps you. I personally do not have any experience with sklearn, I user tensorflow.
About fit() function in sklearn, I made the samples with partial_fit instead which is the stochastic train step (the whole point of this code). 
If you need and could batch-train (fit()), then leave the batch_size parameter to None, this will default the batch size to all and anytime you retrieve a batch, it will give you the whole data.
